// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function Counter(arg1:string):Promise<number>;

export function GetAppConstants():Promise<config.AppConfig>;
