// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Counter(arg1) {
  return window['go']['app']['App']['Counter'](arg1);
}

export function GetAppConstants() {
  return window['go']['app']['App']['GetAppConstants']();
}
